"""
TheCFBAlgo — Streamlit App
Reads predictions_latest.json (generated by predict.py)
Password: Algohubfan1
Run: python -m streamlit run app.py
"""

import streamlit as st
import json, os
from datetime import datetime

st.set_page_config(
    page_title="TheCFBAlgo",
    page_icon="🏈",
    layout="wide",
    initial_sidebar_state="expanded"
)

PASSWORD  = "Algohubfan1"
BASE_DIR  = os.path.dirname(os.path.abspath(__file__))


# ── AUTH ──────────────────────────────────────
def check_password():
    if st.session_state.get("authenticated"):
        return True
    col1, col2, col3 = st.columns([1,2,1])
    with col2:
        st.markdown("<br><br>", unsafe_allow_html=True)
        st.markdown("## 🏈 TheCFBAlgo")
        st.markdown("**Members Only · TheAlgoHub**")
        pw = st.text_input("Access Code", type="password", placeholder="Enter your access code")
        if st.button("Access The Algo →", use_container_width=True, type="primary"):
            if pw == PASSWORD:
                st.session_state.authenticated = True
                st.rerun()
            else:
                st.error("Invalid access code")
        st.caption("Access codes available at TheAlgoHub")
    return False


# ── LOAD DATA ─────────────────────────────────
@st.cache_data(ttl=300)
def load_predictions(week=None):
    # Try week-specific file first, then latest
    if week is not None:
        week_path = os.path.join(BASE_DIR, f"predictions_week{week}.json")
        if os.path.exists(week_path):
            with open(week_path) as f:
                return json.load(f)

    latest = os.path.join(BASE_DIR, "predictions_latest.json")
    if os.path.exists(latest):
        with open(latest) as f:
            return json.load(f)
    return None


# ── EDGE LABEL ────────────────────────────────
def edge_label(val, kind="spread"):
    if val is None: return "—"
    if kind == "spread":
        if abs(val) >= 6:
            return f"🔥 {'HOME' if val>0 else 'AWAY'} +{abs(val):.1f}"
        elif abs(val) >= 3:
            return f"📊 {'HOME' if val>0 else 'AWAY'} +{abs(val):.1f}"
        else:
            return f"~{val:+.1f}"
    elif kind == "total":
        if abs(val) >= 4:
            return f"🔥 {'OVER' if val>0 else 'UNDER'} {abs(val):.1f}"
        elif abs(val) >= 2:
            return f"📊 {'OVER' if val>0 else 'UNDER'} {abs(val):.1f}"
        else:
            return f"~{val:+.1f}"
    elif kind == "ml":
        if abs(val) >= 8:
            return f"🔥 {'HOME' if val>0 else 'AWAY'} +{abs(val):.1f}%"
        elif abs(val) >= 4:
            return f"📊 {'HOME' if val>0 else 'AWAY'} +{abs(val):.1f}%"
        else:
            return f"~{val:+.1f}%"
    return "—"


def edge_color(val):
    if val is None: return "gray"
    if abs(val) >= 6: return "green"
    if abs(val) >= 3: return "orange"
    return "gray"


# ── GAME CARD ─────────────────────────────────
def render_game(g, expanded=False):
    home = g.get("home_team","")
    away = g.get("away_team","")
    ph   = g.get("pred_home","?")
    pa   = g.get("pred_away","?")
    hwp  = g.get("home_win_prob",50)
    awp  = g.get("away_win_prob",50)
    sp   = g.get("book_spread")
    ou   = g.get("book_total")
    hml  = g.get("home_moneyline")
    aml  = g.get("away_moneyline")
    se   = g.get("spread_edge")
    te   = g.get("total_edge")
    mle  = g.get("ml_home_edge")
    ms   = g.get("model_spread")
    pt   = g.get("pred_total")
    wk   = g.get("week","?")

    sp_str  = f"{sp:+.1f}"  if sp  is not None else "N/A"
    ou_str  = f"{ou:.1f}"   if ou  is not None else "N/A"
    ms_str  = f"{ms:+.1f}"  if ms  is not None else "N/A"
    pt_str  = f"{pt:.1f}"   if pt  is not None else "N/A"
    hml_str = f"{hml:+d}"   if hml is not None else "N/A"
    aml_str = f"{aml:+d}"   if aml is not None else "N/A"

    title = f"🏈 Wk{wk}  |  **{home}** {ph} — {pa} **{away}**  |  Spread: {sp_str}  Edge: {edge_label(se)}"

    with st.expander(title, expanded=expanded):
        c1, c2, c3 = st.columns(3)

        with c1:
            st.markdown("**📊 SPREAD**")
            st.metric("Book", sp_str)
            st.metric("Model", ms_str, delta=f"{se:+.1f} edge" if se else None,
                      delta_color="normal" if se and se > 0 else "inverse" if se else "off")
            st.markdown(f"**{edge_label(se,'spread')}**")

        with c2:
            st.markdown("**🎯 TOTAL**")
            st.metric("Book", ou_str)
            st.metric("Model", pt_str, delta=f"{te:+.1f}" if te else None,
                      delta_color="normal" if te and te > 0 else "inverse" if te else "off")
            st.markdown(f"**{edge_label(te,'total')}**")

        with c3:
            st.markdown("**💰 MONEYLINE**")
            st.markdown(f"**{home[:15]}:** {hml_str}")
            st.markdown(f"**{away[:15]}:** {aml_str}")
            st.markdown(f"Home win prob: **{hwp:.0f}%**")
            st.markdown(f"**{edge_label(mle,'ml')}**")

        # Model details
        with st.container():
            d1, d2, d3, d4 = st.columns(4)
            with d1: st.caption(f"Pred: **{ph}—{pa}**")
            with d2: st.caption(f"Home win: **{hwp:.0f}%**")
            with d3: st.caption(f"Away win: **{awp:.0f}%**")
            with d4: st.caption(f"Pred total: **{pt_str}**")


# ── MAIN ──────────────────────────────────────
def main():
    if not check_password():
        return

    st.title("🏈 TheCFBAlgo")
    st.caption("Powered by TheAlgoHub · 2026 Season")

    # Sidebar
    with st.sidebar:
        st.markdown("### 🏈 TheCFBAlgo")
        st.markdown("*TheAlgoHub*")
        st.divider()

        week = st.selectbox(
            "📅 Week",
            options=list(range(0,17)),
            index=1,
            format_func=lambda x: "Week 0 (Kickoff)" if x==0 else f"Week {x}"
        )

        sort_by  = st.selectbox("🔃 Sort by", ["Spread Edge","Total Edge","ML Edge","Week"])
        min_edge = st.slider("🎯 Min Spread Edge", 0.0, 15.0, 0.0, 0.5)

        st.divider()
        if st.button("🔄 Refresh Data"):
            st.cache_data.clear()
            st.rerun()

        st.divider()
        st.markdown("""
        **📖 How to read:**
        - 🔥 Strong edge (6+ pts)
        - 📊 Medium edge (3-6 pts)
        - ~ Low edge (<3 pts)

        **Spread Edge** = Model vs. book line
        **Total Edge** = Model total vs. book
        **ML Edge** = Model win% vs. implied%
        """)

        st.divider()
        st.caption(f"Run `python predict.py {week}` to refresh predictions")

    # Load data
    data = load_predictions(week)

    if data is None:
        st.warning(f"""
        ⚠️ No predictions found for Week {week}.

        Run this on your machine to generate them:
        ```
        python predict.py {week}
        ```
        Then upload `predictions_week{week}.json` to the same folder as `app.py`.
        """)
        return

    games = data.get("games", [])
    gen   = data.get("generated_at","Unknown")
    stats = data.get("model_stats",{})

    # Filter by week if data contains multiple weeks
    if week is not None:
        games = [g for g in games if g.get("week") == week]

    # Apply edge filter
    if min_edge > 0:
        games = [g for g in games if abs(g.get("spread_edge") or 0) >= min_edge]

    # Sort
    if sort_by == "Spread Edge":
        games.sort(key=lambda x: abs(x.get("spread_edge") or 0), reverse=True)
    elif sort_by == "Total Edge":
        games.sort(key=lambda x: abs(x.get("total_edge") or 0), reverse=True)
    elif sort_by == "ML Edge":
        games.sort(key=lambda x: abs(x.get("ml_home_edge") or 0), reverse=True)
    elif sort_by == "Week":
        games.sort(key=lambda x: (x.get("week") or 0))

    # Stats bar
    high = len([g for g in games if abs(g.get("spread_edge") or 0) >= 6])
    med  = len([g for g in games if 3 <= abs(g.get("spread_edge") or 0) < 6])

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Games", len(games))
    c2.metric("🔥 Strong Edges", high)
    c3.metric("📊 Med Edges", med)
    c4.metric("Model ATS", f"{stats.get('ats_pct',0):.1f}%")
    c5.metric("Updated", gen.split(" ")[1] if " " in gen else gen)

    st.divider()
    st.subheader(f"Week {week} — {len(games)} Games")

    if not games:
        st.info("No games match your filters. Try lowering the min edge or running predict.py.")
        return

    tab1, tab2 = st.tabs(["🏈 FBS Games", "📋 FCS Games"])

    with tab1:
        if not games:
            st.info("No games match your filters.")
        else:
            for i, g in enumerate(games):
                render_game(g, expanded=(i < 3))

    with tab2:
        fcs_path = os.path.join(BASE_DIR, f"predictions_fcs_week{week}.json")
        if not os.path.exists(fcs_path):
            st.warning(f"No FCS predictions for Week {week}. Run: python predict_fcs.py {week}")
        else:
            with open(fcs_path) as f:
                fcs_data = json.load(f)
            fcs_games = fcs_data.get("games", [])
            st.info("⚠️ Model trained on FBS data only — FCS predictions are less reliable. Use as a reference.")
            st.caption(f"{len(fcs_games)} FBS vs FCS games with lines")
            if not fcs_games:
                st.write("No FCS games with lines found.")
            else:
                for i, g in enumerate(fcs_games):
                    render_game(g, expanded=(i < 2))

    st.divider()
    st.caption("⚠️ TheCFBAlgo is for entertainment purposes only. Please gamble responsibly. © 2026 TheAlgoHub")


if __name__ == "__main__":
    main()
