"""TheCFBAlgo — Streamlit App (NFL algo layout)
Reads predictions_weekN.json (generated by predict.py)
Password: Algohubfan1
Run: python -m streamlit run app.py
"""
import json
import math
import os
from pathlib import Path

import streamlit as st
import streamlit.components.v1 as components

from cards import render_cards, TIER_RANK, _spread_tier, _total_tier

ROOT     = Path(__file__).resolve().parent
PASSWORD = "Algohubfan1"

st.set_page_config(page_title="TheCFBAlgo", page_icon="🏈", layout="wide")
st.markdown("""<style>
.block-container{padding-top:1.4rem;max-width:1240px}
[data-testid="stMetricValue"]{font-size:1.9rem}
</style>""", unsafe_allow_html=True)


# ── AUTH ──────────────────────────────────────────────────────────────────────
def check_password():
    if st.session_state.get("authenticated"):
        return True
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        st.markdown("<br><br>", unsafe_allow_html=True)
        st.markdown("## 🏈 TheCFBAlgo")
        st.markdown("**Members Only · TheAlgoHub**")
        pw = st.text_input("Access Code", type="password", placeholder="Enter your access code")
        if st.button("Access The Algo →", use_container_width=True, type="primary"):
            if pw == PASSWORD:
                st.session_state.authenticated = True
                st.rerun()
            else:
                st.error("Invalid access code")
        st.caption("Access codes available at TheAlgoHub")
    return False


# ── DATA ──────────────────────────────────────────────────────────────────────
@st.cache_data(ttl=300)
def load_predictions(week):
    week_path = ROOT / f"predictions_week{week}.json"
    if week_path.exists():
        with open(week_path) as f:
            return json.load(f)
    latest = ROOT / "predictions_latest.json"
    if latest.exists():
        with open(latest) as f:
            return json.load(f)
    return None


@st.cache_data(ttl=300)
def load_tracker():
    p = ROOT / "tracker_summary.json"
    if p.exists():
        with open(p) as f:
            return json.load(f)
    return {}


def find_weeks():
    """Return sorted list of available week numbers."""
    weeks = []
    for f in ROOT.glob("predictions_week*.json"):
        try:
            w = int(f.stem.replace("predictions_week", ""))
            weeks.append(w)
        except ValueError:
            pass
    return sorted(weeks, reverse=True)


# ── MAIN ──────────────────────────────────────────────────────────────────────
def main():
    if not check_password():
        return

    st.markdown("#### THE ALGOHUB · CFB GAME ALGO")

    weeks = find_weeks()
    if not weeks:
        st.info("No predictions yet. Run `python predict.py N` to generate Week N predictions.")
        st.stop()

    c1, _ = st.columns([1, 3])
    week = c1.selectbox("Week", weeks, format_func=lambda w: f"2026 · Week {w}",
                        label_visibility="collapsed")

    data = load_predictions(week)
    if data is None:
        st.warning(f"No predictions for Week {week}. Run `python predict.py {week} --push`.")
        st.stop()

    games     = data.get("games", [])
    generated = data.get("generated", data.get("generated_at", ""))
    tracker   = load_tracker()

    t_cards, t_bets, t_record = st.tabs(["Cards", "Best Bets", "Record"])

    # ── CARDS ──────────────────────────────────────────────────────────────
    with t_cards:
        n_days = len({g.get("start_date", "")[:10] for g in games})
        height = 340 + n_days * 70 + math.ceil(len(games) / 3) * 820
        components.html(render_cards(games, week, generated), height=height, scrolling=True)

    # ── BEST BETS ──────────────────────────────────────────────────────────
    with t_bets:
        rows = []
        for g in games:
            mu = f"{g['away_team']} @ {g['home_team']}"
            sp_edge  = g.get("spread_edge")
            tot_edge = g.get("total_edge")
            sp_tier  = _spread_tier(sp_edge)
            tot_tier = _total_tier(tot_edge)
            book_sp  = g.get("book_spread")
            pred_m   = g.get("pred_margin")

            if sp_tier:
                pick = f"{'HOME' if sp_edge > 0 else 'AWAY'} {abs(sp_edge):.1f} pts"
                rows.append(dict(
                    Matchup=mu,
                    Market="Spread",
                    Pick=pick,
                    Tier=sp_tier,
                    Edge=round(sp_edge, 1),
                    Book=f"{book_sp:+.1f}" if book_sp is not None else "-",
                    Model=f"{pred_m:+.1f}" if pred_m is not None else "-",
                ))

            if tot_tier:
                book_tot = g.get("book_total")
                pred_tot = g.get("pred_total")
                tot_pick = f"{'OVER' if tot_edge > 0 else 'UNDER'} {abs(tot_edge):.1f}"
                rows.append(dict(
                    Matchup=mu,
                    Market="Total",
                    Pick=tot_pick,
                    Tier=tot_tier,
                    Edge=round(tot_edge, 1),
                    Book=f"{book_tot:.1f}" if book_tot is not None else "-",
                    Model=f"{pred_tot:.1f}" if pred_tot is not None else "-",
                ))

        if rows:
            import pandas as pd
            bets = pd.DataFrame(rows)
            bets["_r"] = bets.Tier.map(TIER_RANK).fillna(0)
            bets = bets.sort_values(["_r", "Edge"], ascending=False).drop(columns="_r")
            m1, m2, m3 = st.columns(3)
            m1.metric("Strong", int((bets.Tier == "STRONG").sum()))
            m2.metric("Edge",   int((bets.Tier == "EDGE").sum()))
            m3.metric("Lean",   int((bets.Tier == "LEAN").sum()))
            st.dataframe(bets, hide_index=True, use_container_width=True)
            st.caption("Edge = model margin minus book spread (or model total minus book total). Positive = favor favorite/over.")
        else:
            st.info("No plays clear the thresholds this week.")

    # ── RECORD ─────────────────────────────────────────────────────────────
    with t_record:
        overall = tracker.get("overall", {}).get("spread", {})
        w_ats = overall.get("W", 0)
        l_ats = overall.get("L", 0)
        p_ats = overall.get("P", 0)

        if w_ats + l_ats == 0:
            st.info("Nothing graded yet. Results update after games are played.")
        else:
            m1, m2, m3, m4 = st.columns(4)
            m1.metric("ATS Record", f"{w_ats}-{l_ats}-{p_ats}")
            m2.metric("Win %",      f"{w_ats / max(w_ats + l_ats, 1):.1%}")

            by_week = tracker.get("by_week", {})
            if by_week:
                import pandas as pd
                rows_rec = []
                for wk, stats in sorted(by_week.items(), key=lambda x: int(''.join(filter(str.isdigit, str(x[0]))) or 0)):
                    sp = stats.get("spread", {})
                    rows_rec.append({"Week": int(wk), "W": sp.get("W",0), "L": sp.get("L",0),
                                     "P": sp.get("P",0), "Win%": f"{sp.get('pct',0):.1f}%"})
                st.dataframe(pd.DataFrame(rows_rec), hide_index=True, use_container_width=True)

    st.caption("For entertainment. Not betting advice. © 2026 TheAlgoHub")


if __name__ == "__main__":
    main()
